# Generated by Django 5.2.13 on 2026-04-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(max_length=100)),
                ("entity_id", models.PositiveIntegerField(blank=True, null=True)),
                ("activity_type", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "company_type",
                    models.CharField(
                        choices=[
                            ("builder", "Builder"),
                            ("client", "Client"),
                            ("architect", "Architect"),
                            ("project_manager", "Project Manager"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("primary_phone", models.CharField(blank=True, max_length=50)),
                ("primary_email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("suburb", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("role_title", models.CharField(blank=True, max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("mobile", models.CharField(blank=True, max_length=50)),
                (
                    "preferred_contact_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("mobile", "Mobile"),
                        ],
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="FollowUpTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("call", "Call"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                            ("reminder", "Reminder"),
                            ("review", "Review"),
                        ],
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField()),
                ("due_time", models.TimeField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("details", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["due_date", "due_time"],
            },
        ),
        migrations.CreateModel(
            name="LossReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason_category",
                    models.CharField(
                        choices=[
                            ("price", "Price"),
                            ("scope", "Scope"),
                            ("relationship", "Relationship"),
                            ("timing", "Timing"),
                            ("capability", "Capability"),
                            ("competitor", "Competitor"),
                            ("client_change", "Client Change"),
                            ("no_decision", "No Decision"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason_detail", models.TextField(blank=True)),
                ("competitor_name", models.CharField(blank=True, max_length=255)),
                ("price_gap_notes", models.TextField(blank=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project_name", models.CharField(max_length=255)),
                ("project_code", models.CharField(blank=True, max_length=100)),
                ("sector", models.CharField(blank=True, max_length=100)),
                ("opportunity_source", models.CharField(blank=True, max_length=100)),
                ("tender_type", models.CharField(blank=True, max_length=100)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("invited", "Invited"),
                            ("pricing", "Pricing"),
                            ("submitted", "Submitted"),
                            ("follow_up", "Follow Up"),
                            ("negotiating", "Negotiating"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="lead",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("site_suburb", models.CharField(blank=True, max_length=100)),
                (
                    "estimated_contract_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "estimated_margin_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("submission_due_date", models.DateField(blank=True, null=True)),
                ("submission_date", models.DateField(blank=True, null=True)),
                ("expected_award_date", models.DateField(blank=True, null=True)),
                (
                    "probability_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("scope_summary", models.TextField(blank=True)),
                ("inclusions_summary", models.TextField(blank=True)),
                ("exclusions_summary", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "final_awarded_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision_number", models.PositiveIntegerField(default=1)),
                ("quote_reference", models.CharField(blank=True, max_length=100)),
                (
                    "quoted_value_ex_gst",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "quoted_margin_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("submission_date", models.DateField(blank=True, null=True)),
                ("validity_date", models.DateField(blank=True, null=True)),
                (
                    "quote_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("revised", "Revised"),
                            ("withdrawn", "Withdrawn"),
                            ("accepted", "Accepted"),
                            ("unsuccessful", "Unsuccessful"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("assumptions", models.TextField(blank=True)),
                ("exclusions", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["opportunity", "-revision_number"],
            },
        ),
    ]
