# Generated by Django 5.2.13 on 2026-04-11 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pipeline", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="created_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="pipeline.company",
            ),
        ),
        migrations.AddField(
            model_name="followuptask",
            name="assigned_to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="followup_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="assigned_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_opportunities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="opportunities",
                to="pipeline.company",
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="estimator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="estimating_opportunities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="primary_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_for_opportunities",
                to="pipeline.contact",
            ),
        ),
        migrations.AddField(
            model_name="lossreason",
            name="opportunity",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loss_reason",
                to="pipeline.opportunity",
            ),
        ),
        migrations.AddField(
            model_name="followuptask",
            name="opportunity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="pipeline.opportunity",
            ),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="opportunity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to="pipeline.opportunity",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="opportunity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to="pipeline.opportunity",
            ),
        ),
        migrations.AddField(
            model_name="followuptask",
            name="related_quote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="pipeline.quote",
            ),
        ),
        migrations.AddConstraint(
            model_name="quote",
            constraint=models.UniqueConstraint(
                fields=("opportunity", "revision_number"),
                name="unique_quote_revision_per_opportunity",
            ),
        ),
    ]
