# Generated by Django 5.2.13 on 2026-04-11 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.AlterModelOptions(
            name="opportunity",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Opportunity",
                "verbose_name_plural": "Opportunities",
            },
        ),
    ]
