# Generated by Django 5.2.13 on 2026-04-24 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0005_archived_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="project_code",
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="opportunity",
            constraint=models.UniqueConstraint(
                fields=("project_code", "company"),
                name="unique_project_code_per_company",
            ),
        ),
    ]
