# Generated by Django 5.2.13 on 2026-04-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0007_followup_completion_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lossreason",
            name="reason_category",
            field=models.CharField(
                choices=[
                    ("price", "Price"),
                    ("scope", "Scope"),
                    ("relationship", "Relationship"),
                    ("timing", "Timing"),
                    ("capability", "Capability"),
                    ("competitor", "Competitor"),
                    ("client_change", "Client Change"),
                    ("no_decision", "No Decision"),
                    ("project_won_other", "Project Won via Another Builder"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
