# Generated by Django 5.2.15 on 2026-06-17 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0008_loss_reason_project_won_other"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="account_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_accounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="account_tier",
            field=models.CharField(
                blank=True,
                choices=[("A", "Tier A"), ("B", "Tier B"), ("C", "Tier C")],
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="last_contact_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="margin_quality",
            field=models.CharField(
                blank=True,
                choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="next_contact_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="relationship_notes",
            field=models.TextField(blank=True),
        ),
        # Drop the accounts_builder and accounts_contact tables that
        # were created by the now-removed apps/accounts app. Safe if
        # the tables never existed (e.g. fresh installs).
        migrations.RunSQL(
            sql=[
                "DROP TABLE IF EXISTS accounts_contact CASCADE;",
                "DROP TABLE IF EXISTS accounts_builder CASCADE;",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
