# Generated by Django 5.2.15 on 2026-06-21 22:46

from django.db import migrations, models


_RENAMES = {
    "client_change": "cancelled",
    "no_decision": "no_response",
    "timing": "other",
    "capability": "other",
}


def _migrate_old_values(apps, schema_editor):
    """Convert historic loss-reason values to the new standardised set."""
    LossReason = apps.get_model("pipeline", "LossReason")
    for old, new in _RENAMES.items():
        updated = LossReason.objects.filter(reason_category=old).update(
            reason_category=new
        )
        if updated:
            print(f"  loss_reason: {old} → {new}  ({updated} row(s))")


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0009_company_account_mgmt_fields"),
    ]

    operations = [
        # Step 1: rename historic values in the data before the schema
        # change narrows the allowed set.
        migrations.RunPython(
            _migrate_old_values,
            reverse_code=migrations.RunPython.noop,
        ),
        # Step 2: apply the new choices.
        migrations.AlterField(
            model_name="lossreason",
            name="reason_category",
            field=models.CharField(
                choices=[
                    ("price", "Price"),
                    ("program", "Program"),
                    ("scope", "Scope / exclusions"),
                    ("relationship", "Relationship"),
                    ("competitor", "Competitor / incumbent"),
                    ("cancelled", "Client cancelled"),
                    ("no_response", "No response / went cold"),
                    ("project_won_other", "Project Won via Another Builder"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
