# Generated by Django 5.2.16 on 2026-07-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0010_standardise_loss_reason_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="award_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
